[package]
name = "smart-road"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
sdl2 = { version = "0.34.5", features = ["image"] }
rand = "0.8"
uuid = { version = "1.2", features = ["v4"] }
